### ISSUE TITLE
Fails for files encoded with a different locale

### ISSUE THREAD

**Issue by p2jones** [bcliang/gamry-parser#12]
Gamry files are created with local number formatting. For example, in Germany and much of the world, the [comma is used a decimal separator](https://en.wikipedia.org/wiki/Decimal_separator#/media/File:DecimalSeparator.svg). So a value would be 8,47309E-004 in the DTA file.

This can be partly solved with `import locale` in the header and replacing `float` with `locale.atof` in `read_header`. Then any file using gamry-parser can set the locale:

```
import gamry_parser as parser
import locale
locale.setlocale(locale.LC_ALL, 'de_DE')

file = 'CV.DTA'
gp = parser.GamryParser()
gp.load(filename=file)
```

However, a problem remains. `read_curves` uses the following line:
```
temp = temp.apply(pd.to_numeric, errors='ignore')
```
This doesn't use the locale. It doesn't give an error, but numbers with a comma decimal remain as strings. I'm not sure what the best way to solve this is.

**Comment by p2jones** [comment]
A temporary solution is to convert the strings to numbers separately with the locale.atof function. For example:
```
file = 'data.DTA'
cv = parser.CyclicVoltammetry(filename=file)
cv.load()
curve = cv.get_curve_data(2)
print(curve)
```
The data remains with dtype object, with comma as decimal in the strings:
```
                 Vf             Im
Pt                                
0     -2,03820E-001   4,45797E-008
1     -2,01872E-001   1,27799E-007
2     -1,99947E-001   1,99196E-007
```
With this change, the problem is fixed:
```
curve = curve.applymap(locale.atof)
print(curve)
```
The data now has dtype float64:
```
            Vf            Im
Pt                          
0    -0.203820  4.457970e-08
1    -0.201872  1.277990e-07
2    -0.199947  1.991960e-07
```

**Comment by bcliang** [comment]
Thanks for opening the issue. I guess you can tell I'm US-based. 

Let me think on a locale-aware solution; applying `locale.atof` as you've suggested could be a quick fix, not sure about what would be best practice. Alternatively, I'm happy to accept a PR for a fix.

**Comment by p2jones** [comment]
I'm surprised that there's no standard for storing data. Depending on software, I see data with either commas or periods as decimals or thousands separators. It can be tough to know what the numbers really are.

I've forked the package and seem to have a working solution. I've also added functionality to read in units, and solved an issue for when CVs include a first measurement of OCV.

Is there an important reason to use one-based indexing? I'd prefer to use zero-based indexing (e.g. _n_ cycles from 0 to _n_-1) to be consistent with other python packages. (in my forked version, I've switched to zero-based indexing)

**Comment by p2jones** [comment]
The units always match so far, but I've only tested with a limited set of files. I don't know if the files can be saved in other units. In my script, I also check that units are V and A (to avoid any unpleasant surprises):
```
assert cv.curve_units['Vf'] == 'V vs. Ref.', 'Unexpected units!'
assert cv.curve_units['Im'] == 'A', 'Unexpected units!'
```
Using the quantities package would be a nice addition.

Should I make a pull request?
