### ISSUE TITLE
Load OCV Curve Data

### ISSUE THREAD

**Issue by bcliang** [bcliang/gamry-parser#15]
Currently, OCVCURVE data is ignored by the parser (#13). 

Instead, (if it exists) the OCV data should be kept and made accessible to the user.

Currently:
- bool `self.ocv_curve` indicates if the DTA file contained an OCV curve in the header. 

Fix:
- persist OCVCURVE data. The curve table is expected to take the form:
```
OCVCURVE	TABLE	[__a_number__]
	Pt	T	Vf	Vm	Ach	Over
	#	s	V vs. Ref.	V	V	bits
```
- provide a function to retrieve the time-series OCV data, if it exists
- provide a function to indicate whether OCV data has been loaded

**Comment by bcliang** [comment]
The OCVCURVE table appears to be generated in framework 6.xx. 

As of Gamry Framework 7.07, the OCVCURVE table is not generated. Instead, we can look to 2 lines indicating activity:
1. `DELAY	TWOPARAM	T	[time, seconds]	[rate, mV/s]	Init. De&lay	Time(s)	Stab.(mV/s)`
2. `EOC	QUANT	0.2834373	Open Circuit (V)`

**DELAY** indicates the desired stability threshold before the test may commence, and
**EOC** indicates the final OCV reading (in V)

Related to this, data from any CONDITIONING period is not saved by framework (run chronoamperometry for a specific amount of time before starting the experiment)
`CONDIT	TWOPARAM	T	[time, seconds]	[operating potential, V]	Conditionin&g	Time(s)	E(V)`

**Comment by p2jones** [comment]
Do you have documentation for different versions of DTA files? I've found this [description](https://www.gamry.com/application-notes/software-scripting/dta-file-type/) but no details for different versions (6.xx or 7.xx).

**Comment by bcliang** [comment]
Unfortunately not. It just happens that some potentiostats that we use are on older licenses that cannot run with the newer framework version.

I put together most of the package based on real DTA files as well as Gamry's [Framework Help Reference](https://www.gamry.com/Framework%20Help/HTML5%20-%20Tripane%20-%20Audience%20A/framework_help.htm#FW/Gamry_Framework_Library_Routines/Description%20of%20Library%20Routines.htm%3FTocPath%3DFramework%7CGamry%2520Framework%2520Library%2520Routines%7C_____1)

**Comment by bcliang** [comment]
I have an initial implementation for this that returns either the contents of the ocvcurve table (or header param EOC), or None. Doesn't currently perform any number formatting, but will make sure it's locale-aware. 

https://github.com/bcliang/gamry-parser/tree/ocvcurve-and-missing-tests

Once this feature is merged (along with tests), I'll rev the version of the package to 0.3.x
