### ISSUE TITLE
handling string during file loading

### ISSUE THREAD

**Issue by Mossybeam** [bcliang/gamry-parser#47]
Hello everyone,

sorry if this is a newbie question, but upon loading the file, I run into a 'could not convert string to float: '0,00000E+000' error.
My Gamry outpul .DATA files contain scientific notation of numbers and apparently the loading of the file and conversion to pd.dataframe has an issue with that.
What were your solutions/what am I doing wrong?

Thanks for any advice

**Comment by bcliang** [comment]
@Mossybeam -- any chance you can share a snippet of the data file? Thanks.

**Comment by wotgit** [comment]
> Hello everyone,
> 
> sorry if this is a newbie question, but upon loading the file, I run into a 'could not convert string to float: '0,00000E+000' error. My Gamry outpul .DATA files contain scientific notation of numbers and apparently the loading of the file and conversion to pd.dataframe has an issue with that. What were your solutions/what am I doing wrong?
> 
> Thanks for any advice

Hi! 
I'm having the same issue has there been found a solution already?

**Comment by bcliang** [comment]
@wotgit Any chance you can post a sample data file? You can remove any sensitive information from the file if needed.

**Comment by wotgit** [comment]
Sure! Here is one to test with. https://we.tl/t-vwr9533K2g

**Comment by bcliang** [comment]
@wotgit @Mossybeam 
I looked at the file supplied by wotgit. I was able to properly load the EISPOT curves by defining an appropriate locale. Here is a minimal example that loads the curves properly:

```python
import locale
import gamry_parser as parser

# set the desired locale
locale.setlocale(locale.LC_ALL, "de_DE.utf8")

# parse the data using the Impedance subclass
eis = parser.Impedance(filename="SampleData.DTA")
eis.load()

..
# do something with the data
```
This should work for any DTA file. Hope this helps.

**Comment by wotgit** [comment]
@bcliang thanks for your answer! I'm trying your example but I'm getting the following error:
eis = parser.Impedance(filename=path)
          ^^^^^^
NameError: name 'parser' is not defined

**Comment by bcliang** [comment]
@wotgit Apologies. I updated the example with the import statement `import gamry_parser as parser`

**Comment by wotgit** [comment]
@bcliang thanks it works now!
